
disabled_rules:
    - trailing_whitespace
    - vertical_whitespace
    - unused_optional_binding
    - line_length
    - unused_closure_parameter
    - trailing_comma
    - trailing_newline
    - todo
    - file_length
    - force_try
    - function_body_length
    - function_parameter_count
    - large_tuple
    - type_body_length
    - type_name
    - cyclomatic_complexity
    - identifier_name
    - nesting
    - weak_delegate
    - colon
    - multiple_closures_with_trailing_closure
    - private_over_fileprivate
    - fallthrough
    - unused_setter_value
    - reduce_boolean
    - unused_capture_list
    - deployment_target
    - legacy_hashing
    - inert_defer
    - vertical_parameter_alignment
    - redundant_string_enum_value
    - legacy_constructor
    - implicit_getter
    - syntactic_sugar
    - for_where
    - overridden_super_call
included:
    - ./GachaApp
    - ./GachaAppTests
excluded:
    - ./GachaApp/UIResource/Generated
    - ./GachaAppTests/SwiftLintFrameworkTests/Resources
opt_in_rules:
    - empty_string
    - empty_count
    - file_header
    - force_cast
    - explicit_init
    - closure_spacing
    - redundant_nil_coalescing
    - private_outlet
    - nimble_operator
    - attributes
    - operator_usage_whitespace
    - closure_end_indentation
    - first_where
    - sorted_imports
    - object_literal
    - number_separator
    - prohibited_super_call
    - fatal_error_message

